"""Generate README, local artwork, and site content from profile.json. Requires Pillow."""
from pathlib import Path
import json, math, html, shutil
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
P = json.loads((ROOT / 'profile.json').read_text(encoding='utf-8'))
ASSETS = ROOT / 'assets'
ASSETS.mkdir(exist_ok=True)
def font(size, bold=False):
    candidates = ['C:/Windows/Fonts/seguisb.ttf' if bold else 'C:/Windows/Fonts/segoeui.ttf', '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf' if bold else '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf']
    for path in candidates:
        if Path(path).exists(): return ImageFont.truetype(path, size)
    return ImageFont.load_default(size=size)

def hero():
    frames=[]
    for frame in range(48):
        im=Image.new('RGB',(1200,430),P['theme']['background']);d=ImageDraw.Draw(im)
        d.line((40,390,1160,390),fill='#30353f')
        d.text((52,43),'SAYED / PLAYLAB',font=font(15,True),fill=P['theme']['accent'])
        d.text((48,98),P['name'],font=font(76,True),fill='#f2f3ed')
        d.text((52,203),P['headline'],font=font(30),fill='#b9bfcb')
        d.text((52,294),'UNITY   /   UNREAL ENGINE   /   ROBLOX',font=font(17,True),fill=P['theme']['accent'])
        d.text((52,348),'GAMEPLAY  ·  MULTIPLAYER  ·  VR & SIMULATION',font=font(13),fill='#9299a6')
        theta=frame/48*2*math.pi
        cx,cy=955,202
        # Rotating wireframe sphere: original procedural artwork, no external asset.
        for latitude in range(-60,61,20):
            phi=math.radians(latitude);pts=[]
            for longitude in range(0,361,6):
                a=math.radians(longitude)+theta
                x=math.cos(phi)*math.cos(a);y=math.sin(phi);z=math.cos(phi)*math.sin(a)
                scale=130*(1+z*.10);pts.append((cx+x*scale,cy+(y*.93+z*.24)*scale))
            d.line(pts,fill='#687d40',width=1)
        for longitude in range(0,180,20):
            pts=[]
            for latitude in range(0,361,4):
                a=math.radians(longitude)+theta;b=math.radians(latitude)
                x=math.cos(b)*math.cos(a);y=math.sin(b);z=math.cos(b)*math.sin(a)
                pts.append((cx+x*130,cy+(y*.93+z*.24)*130))
            d.line(pts,fill=P['theme']['accent'],width=1)
        angle=theta
        px=cx+170*math.cos(angle);py=cy+58*math.sin(angle)
        d.ellipse((cx-170,cy-58,cx+170,cy+58),outline='#514667',width=1)
        d.ellipse((px-8,py-8,px+8,py+8),fill=P['theme']['secondary'])
        d.text((840,351),'IMAGINATION → INTERACTION',font=font(12),fill='#9299a6')
        frames.append(im)
    frames[0].save(ASSETS/'hero.gif',save_all=True,append_images=frames[1:],duration=85,loop=0,optimize=True)

def cover(g):
    im=Image.new('RGB',(800,500),'#151922');d=ImageDraw.Draw(im);accent=g.get('accent',P['theme']['accent'])
    for i in range(16):
        radius=45+i*15
        d.ellipse((400-radius,250-radius*.6,400+radius,250+radius*.6),outline='#2d3440',width=2)
    d.text((35,27),g['platform'].upper()+' / SELECTED WORK',font=font(18,True),fill=accent)
    d.text((270,112),g.get('symbol','✳'),font=font(155,True),fill=accent)
    d.line((35,433,765,433),fill='#39414c',width=2)
    d.text((35,454),'CONTRIBUTED TO THIS GAME',font=font(13),fill='#a0a9b7')
    d.text((720,440),'↗',font=font(38),fill=accent)
    im.save(ASSETS/(g['id']+'.png'))

def md(text): return str(text).replace('|','\\|').replace('\n',' ')
def a(label,url): return f'<a href="{html.escape(url,quote=True)}">{html.escape(label)}</a>'
def readme():
    out=['<!-- Generated by scripts/build_profile.py. Edit profile.json, then rebuild. -->',f'<p align="center"><img src="assets/hero.gif" alt="{html.escape(P["name"])} — {html.escape(P["headline"])}" width="100%"></p>',f'<p align="center"><strong>Unity · Unreal Engine · Roblox · Multiplayer · VR</strong></p>',f'<p align="center">{html.escape(P["bio"])}</p>',f'<p align="center">{a("▶ PLAY NEON SNAKE",P["siteUrl"]+"#arcade")} &nbsp; / &nbsp; {a("EXPLORE MY WORK ↗",P["siteUrl"])} &nbsp; / &nbsp; {a("LET’S TALK ↗","mailto:"+P["email"])}</p>','## Selected work','Games I’ve worked on — Roblox worlds, mobile games, and interactive experiences.','<table><tr>']
    for g in [g for g in P['games'] if g.get('featured')]:
        out.append(f'<td width="33%" valign="top"><a href="{html.escape(g["url"],quote=True)}"><img src="assets/{g["id"]}.png" alt="{html.escape(g["title"])}" width="100%"></a><br><sub>{html.escape(g["platform"].upper())}</sub><br><strong>{html.escape(g["title"])}</strong><br><br>{a("Visit game ↗",g["url"])}</td>')
    out+=['</tr></table>','| More games | Platform |','| :--- | :--- |']
    for g in P['games']:
        if not g.get('featured'):out.append(f'| [{md(g["title"])} ↗]({g["url"]}) | {md(g["platform"])} |')
    out+=['## The toolkit','<table><tr>']
    for skill in P['skills']:
        out.append(f'<td valign="top"><strong>{html.escape(skill["category"])}</strong><br><br>'+ '<br>'.join(html.escape(s) for s in skill['items'])+'</td>')
    out+=['</tr></table>','## Built beyond the screen']
    for w in P['worlds']:out.append(f'**[{md(w["title"])} ↗]({w["url"]})** · {md(w["description"])}  <br>')
    out+=['## A little less scrolling. A little more playing.',f'**[Play Neon Snake →]({P["siteUrl"]}#arcade)** — keyboard, touch controls, and a personal best. Runs on the companion page.', '## Contribution trail','<picture><source media="(prefers-color-scheme: dark)" srcset="assets/contributions-dark.svg"><img src="assets/contributions.svg" alt="GitHub contribution snake animation" width="100%"></picture>',f'<p align="center">{a("Portfolio",P["portfolio"])} · {a("LinkedIn",P["linkedin"])} · {a("Email","mailto:"+P["email"])}</p>']
    (ROOT/'README.md').write_text('\n\n'.join(out)+'\n',encoding='utf-8')

if __name__=='__main__':
    hero()
    for g in P['games']: cover(g)
    readme()
    # Honest first-run state. The scheduled workflow replaces these with real contribution data.
    for name in ['contributions.svg','contributions-dark.svg']:
        path=ASSETS/name
        if not path.exists():path.write_text('<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="90"><rect width="1200" height="90" rx="12" fill="#151922"/><text x="40" y="52" fill="#9299a6" font-family="sans-serif" font-size="18">Contribution snake appears after the first Profile refresh workflow run.</text></svg>',encoding='utf-8')
    (ROOT/'site'/'profile.json').write_text(json.dumps(P,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
    shutil.copytree(ASSETS,ROOT/'site'/'assets',dirs_exist_ok=True)
    print('Built README, animated GIF, game cards and site content.')
